using System;
using UnityEngine;

// Note: This class expects there is an existing PlayerControls generated by the Input System
// and that callers will reference this MonoBehaviour (e.g. via inspector) as an IInputProvider.
public class UnityInputProvider : MonoBehaviour, IInputProvider
{
    [SerializeField] private PlayerControls controlsAsset;

    public Vector2 Move { get; private set; }

    public event Action<Vector2> OnMovePerformed;
    public event Action OnMoveCanceled;

    public event Action OnJumpPressed;
    public event Action OnDashPressed;
    public event Action OnInteractPressed;
    public event Action OnAttackPressed;

    private PlayerControls controls;

    private void Awake()
    {
        controls = controlsAsset != null ? controlsAsset : Player.instance.controls;

        // Bind input callbacks
        controls.Player.Move.performed += ctx => HandleMove(ctx.ReadValue<Vector2>());
        controls.Player.Move.canceled += ctx => HandleMoveCanceled();

        controls.Player.Jump.performed += ctx => OnJumpPressed?.Invoke();
        controls.Player.Dash.performed += ctx => OnDashPressed?.Invoke();
        controls.Player.Interact.performed += ctx => OnInteractPressed?.Invoke();
        controls.Player.Attack.performed += ctx => OnAttackPressed?.Invoke();
    }

    private void OnDestroy()
    {
        if (controls == null) return;
        // Unsubscribe to avoid potential dangling delegates
        controls.Player.Move.performed -= ctx => HandleMove(ctx.ReadValue<Vector2>());
        controls.Player.Move.canceled -= ctx => HandleMoveCanceled();

        controls.Player.Jump.performed -= ctx => OnJumpPressed?.Invoke();
        controls.Player.Dash.performed -= ctx => OnDashPressed?.Invoke();
        controls.Player.Interact.performed -= ctx => OnInteractPressed?.Invoke();
        controls.Player.Attack.performed -= ctx => OnAttackPressed?.Invoke();
    }

    private void HandleMove(Vector2 v)
    {
        Move = v;
        OnMovePerformed?.Invoke(v);
    }

    private void HandleMoveCanceled()
    {
        Move = Vector2.zero;
        OnMoveCanceled?.Invoke();
    }
}

